### ISSUE TITLE
Elastix 4.8

### ISSUE THREAD

**Issue by JorritPosthuma** [kaspermarstal/SimpleElastix#3] opened 2015-10-14 15:34 UTC
Hi!

Do you think it is easy to update to Elastix 4.8? I would love to use the new `OpenCL` filters 😊
In addition, for me, it would also be helpful to have access to the number of threads Elasix uses.

**Comment by JorritPosthuma** [comment] 2015-10-14 15:49
Btw, SimpleElastix deserves to be added to http://elastix.bigr.nl/wiki/index.php/Additional_tools :wink:

**Comment by kaspermarstal** [comment] 2015-10-14 22:32
Yes, upgrading to 4.8 should be fairly easy. Will keep this pull request open until it is merged. Stay tuned :) 

With respect to the number of threads, that option is not available because it is not exposed by the elastix API. Sorry :/

**Comment by kaspermarstal** [comment] 2015-10-16 12:41
You can now checkout the development branch to get SimpleElastix with Elastix 4.8. Would you mind running the test suite (i.e. "make test" in the SimpleITK-build directory)?

**Comment by JorritPosthuma** [comment] 2015-10-20 13:21
Yes!! Will do :smile:

**Comment by JorritPosthuma** [comment] 2015-10-20 13:56
While compiling, I get the following error:

```
[ 66%] Built target SimpleITKCommon
Scanning dependencies of target SimpleElastix
Scanning dependencies of target SimpleTransformix
[ 66%] Building CXX object Code/Elastix/src/CMakeFiles/SimpleTransformix.dir/sitkSimpleTransformix.cxx.o
[ 66%] Building CXX object Code/Elastix/src/CMakeFiles/SimpleElastix.dir/sitkSimpleElastix.cxx.o
In file included from /Users/Jorrit/Development/SELX 4.8/Source/Code/Elastix/src/sitkSimpleTransformix.cxx:4:
/Users/Jorrit/Development/SELX 4.8/Source/Code/Elastix/include/sitkSimpleTransformix.h:10:10: fatal error: 'transformixlib.h' file not found
#include "transformixlib.h"
         ^
In file included from /Users/Jorrit/Development/SELX 4.8/Source/Code/Elastix/src/sitkSimpleElastix.cxx:4:
/Users/Jorrit/Development/SELX 4.8/Source/Code/Elastix/include/sitkSimpleElastix.h:10:10: fatal error: 'elastixlib.h' file not found
#include "elastixlib.h"
         ^
1 error generated.
1 error generated.
make[5]: *** [Code/Elastix/src/CMakeFiles/SimpleTransformix.dir/sitkSimpleTransformix.cxx.o] Error 1
make[4]: *** [Code/Elastix/src/CMakeFiles/SimpleTransformix.dir/all] Error 2
make[4]: *** Waiting for unfinished jobs....
make[5]: *** [Code/Elastix/src/CMakeFiles/SimpleElastix.dir/sitkSimpleElastix.cxx.o] Error 1
make[4]: *** [Code/Elastix/src/CMakeFiles/SimpleElastix.dir/all] Error 2
make[3]: *** [all] Error 2
make[2]: *** [SimpleITK-prefix/src/SimpleITK-stamp/SimpleITK-build] Error 2
make[1]: *** [CMakeFiles/SimpleITK.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by PertuyF** [comment] 2015-10-20 14:39
Hi Jorrit,

Did you compiled ElastiX yourself or do you use the SuperBuild ?

If you use a system version of ElastiX (compile it yourself and USE_SYSTEM_ELASTIX) be sure to use the version from Kasper’s repository<https://github.com/kaspermarstal/elastix/tree/master>
The one from “mstaring/elastix” won’t work for building SimpleElastiX.


Fabien


De : Jorrit Posthuma [mailto:notifications@github.com]
Envoyé : mardi 20 octobre 2015 15:56
À : kaspermarstal/SimpleElastix <SimpleElastix@noreply.github.com>
Objet : Re: [SimpleElastix] Elastix 4.8 (#3)


While compiling, I get the following error:

[ 66%] Built target SimpleITKCommon

Scanning dependencies of target SimpleElastix

Scanning dependencies of target SimpleTransformix

[ 66%] Building CXX object Code/Elastix/src/CMakeFiles/SimpleTransformix.dir/sitkSimpleTransformix.cxx.o

[ 66%] Building CXX object Code/Elastix/src/CMakeFiles/SimpleElastix.dir/sitkSimpleElastix.cxx.o

In file included from /Users/Jorrit/Development/SELX 4.8/Source/Code/Elastix/src/sitkSimpleTransformix.cxx:4:

/Users/Jorrit/Development/SELX 4.8/Source/Code/Elastix/include/sitkSimpleTransformix.h:10:10: fatal error: 'transformixlib.h' file not found

#include "transformixlib.h"

         ^

In file included from /Users/Jorrit/Development/SELX 4.8/Source/Code/Elastix/src/sitkSimpleElastix.cxx:4:

/Users/Jorrit/Development/SELX 4.8/Source/Code/Elastix/include/sitkSimpleElastix.h:10:10: fatal error: 'elastixlib.h' file not found

#include "elastixlib.h"

         ^

1 error generated.

1 error generated.

make[5]: *** [Code/Elastix/src/CMakeFiles/SimpleTransformix.dir/sitkSimpleTransformix.cxx.o] Error 1

make[4]: *** [Code/Elastix/src/CMakeFiles/SimpleTransformix.dir/all] Error 2

make[4]: *** Waiting for unfinished jobs....

make[5]: *** [Code/Elastix/src/CMakeFiles/SimpleElastix.dir/sitkSimpleElastix.cxx.o] Error 1

make[4]: *** [Code/Elastix/src/CMakeFiles/SimpleElastix.dir/all] Error 2

make[3]: *** [all] Error 2

make[2]: *** [SimpleITK-prefix/src/SimpleITK-stamp/SimpleITK-build] Error 2

make[1]: *** [CMakeFiles/SimpleITK.dir/all] Error 2

make: *** [all] Error 2

**Comment by JorritPosthuma** [comment] 2015-10-20 14:53
I use the SuperBuild, but do use the USE_SYSTEM_SWIG flag.

**Comment by kaspermarstal** [comment] 2015-10-20 20:37
Unfortunately I am unable to reproduce the issue on OS X 10.11. It may be worth starting over with a fresh clone and build directory and use "SELX4.8" instead of "SELX 4.8" to see if the space in the path is causing the issue. If this doesn't work, can you post the contents of your SimpleElastixBuild/elastix-build/src/UseElastix.cmake file?

**Comment by JorritPosthuma** [comment] 2015-10-20 20:39
Very good point! Going to try it directly 😋

**Comment by JorritPosthuma** [comment] 2015-10-20 21:22
Yes!! It compiles! I'll let it run for the night and run `make test` in the morning 😊.

**Comment by JorritPosthuma** [comment] 2015-10-21 09:36
`100% tests passed, 0 tests failed` :tada:

**Comment by kaspermarstal** [comment] 2015-10-21 11:19
:metal:

**Comment by kaspermarstal** [comment] 2015-10-21 11:19
Thanks for testing!

**Closed by kaspermarstal** 2015-10-21 11:19 UTC
Labels: enhancement
