### ISSUE TITLE
LogToConsoleOff not working?

### ISSUE THREAD

**Issue by t-sanders** [kaspermarstal/SimpleElastix#21] opened 2016-03-01 11:21 UTC
LogToConsoleOff does not work whereas LogToFolderOff works as expected.

The output to console seems to be unstoppable ;-)

**Comment by kaspermarstal** [comment] 2016-03-01 13:13
The problem is related to how elastix handles output internally. Some global variables are not deleted after elastix has run. If you restart your python session LogToConsole will be reset. 

This will be fixed in the next release. I hope you can cope with this issue until then!

**Comment by t-sanders** [comment] 2016-03-01 20:51
Restarting python session has no effect. LogToConsole is always on...

**Comment by kaspermarstal** [comment] 2016-03-01 22:58
Can you show me a minimum viable example that reproduces the issue? And which branch are you on?

**Comment by t-sanders** [comment] 2016-03-02 10:43
The HelloWorld program illustrates the problem: LogToConsoleOff has no effect on SimpleElastix and SimpleTransformix and is default On. 

I am running on Ubuntu 14.04 64bit/16Gb Ram.
I checked out with "git clone https://github.com/kaspermarstal/SimpleElastix" (as suggested in the manual). Gues that's the main branch.

**Comment by kaspermarstal** [comment] 2016-05-12 09:07
This problem should now be fixed. Try again and let me know how it goes.

**Comment by kaspermarstal** [comment] 2016-05-30 11:30
Closing. Feel free to re-open if you run into this issue again.

**Closed by kaspermarstal** 2016-05-30 11:30 UTC
